### ISSUE TITLE
Compile it?

### ISSUE THREAD

**Issue by th3bytre** [BasedBased/ChromiumStealer#9]
How to compile it to one EXE file

**Comment by ghost** [comment]
Try nuitka, it's a normal compiler and I have 0 detects now

**Comment by ksdodk** [comment]
not made for your intentions

**Comment by th3bytre** [comment]
> not made for your intentions
Of course, i follow the rule

**Comment by BasedBased** [comment]
compilers like pyinstaller or nuitka will always trigger AV, python is one of the worst languages for Malware because it is not precompiled
